#!/bin/bash

# Copyright (C) 2016 Adam Makepeace
# Email: adam.makepeace@hotmail.co.uk
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

bus=$( env | grep DBUS_SESSION_BUS_ADDRESS )
if [ ! -d $HOME/.amwaketool ]; then mkdir $HOME/.amwaketool; fi
echo -n $bus > $HOME/.amwaketool/dbus_session_bus_address
chmod 600 $HOME/.amwaketool/dbus_session_bus_address

